### ISSUE TITLE
Introduce .handle_inadmissible argument to testMGD and testOMF

### ISSUE THREAD

**Issue by Klesel** [M-E-Rademaker/cSEM#129]
add argument .handle_inadmissible for the test functions:
- [x] testOMF
- [x] testMGD

**Comment by FloSchuberth** [comment]
The structure of the two test functions is currenlty different it needs to harmonized. @M-E-Rademaker : Please decide which solution you prefer and adjust the corresponding test function. Moreover, the names of the output need to be adjusted as Number_of_admissibles is not correct anymore. 
The print methods needs to be adjusted as well.

**Comment by M-E-Rademaker** [comment]
Some questions/suggestions/proposals

1. I think the argument `.show_progress` can be dropped. Reason: I dont know why you would ever want it to be `FALSE`? 
2. Handle inadmissibles has choices "drop" (always the default) "ignore" and _"replace"_ (instead of "fill"). I think "replace" most clearly says what it does.
3. If I understood correctly, it makes sense to run `testMGD( )` with `.type_vcv = "construct"`, so the argument needs to stay. Does it also make sense for `testOMF()`? I dont see why not but @FloSchuberth you explicitly set the argument to "indicator" so i suppose there is a reason why this is not meaningful?
4. I will make the functions generic with methods for object of class `cSEMResults_default`, `cSEMResults_multi` and `cSEMResults_2ndorder`. This wont break any of your code. Just be aware that the functions will look different.

**Comment by FloSchuberth** [comment]
We should also add a check whether the given arguments are correct, e.g., for .handle._inadmissibles....

**Comment by M-E-Rademaker** [comment]
yes. Use `match.arg()`.
