### ISSUE TITLE
Replace . by : in the formula to highlight higher-order and interaction effects

### ISSUE THREAD

**Issue by FloSchuberth** [M-E-Rademaker/cSEM#192]
We should use : instead of . as this in line with lavaan

**Comment by M-E-Rademaker** [comment]
Unfortunately this does not work, since lavaan does not seem to support "interactions with itself". Specifiying e.g. `IMAG:IMAG` is parsed by lavaan to `IMAG:NA`. Only if the first and the second term are different does the colon operator work. Since I dont see no point in rewriting lavaan's `lavaanify()` function, I think we should stick with the dot.
