### ISSUE TITLE
how to fit second order composite formed through several first order composites

### ISSUE THREAD

**Issue by shaan2020** [M-E-Rademaker/cSEM#420]
Requesting for help with codes for a composite -composite 2nd order construct

Dear Sir,

Hope this mail finds you well in these turbulent times. 

I was planning to use cSEM package in R for a scale development study. 

However after running through several tutorials on the net, i could not figure out how to fit to data in my model. 

I have a composite 2nd order factor B, developed through 6 other 1st order composites. 

I could not figure out how to use the repeated indicator approach.

 Further when i load all the indicators of the 6 first order composites on 2nd order as a repeated measure, its showing me" at least one indicator is connected to more than one construct". 

If i give different names of the relevant indicators like " item 1-item 20" and load on 2nd order composite  and run the model: 
I get the verify(result) step okay across all the 5 steps. 

However , then when i give any other command, testOMF(result), etc, i get the below error: 
Lapack routine dgesv: system is exactly singular: U[20,20] = 0

Can you please help me with some example to show the codes for this study? 

Waiting in anticipation.

**Comment by FloSchuberth** [comment]
Dear @shaan2020 ,

first of all scale development is usually done with classical CFA. However, as you deal with composites, cSEM might be a valuable package to consider.

Is your second-order connected to an antecedent or a consequence? If not, your model is not identified, see Schuberth et al. (2020). 

Moreover, the repeated indicators approach is not implemented, hence to use it, you have to replicate the indicators manually. In doing so, make sure that you avoid double naming as these can lead to problems. It seems that you have already done that.

If you want to test a model based on the repeated indicators approach, you will face problems as this is not the actual model you are interested in. You have added the repeated indicators as a workaround to estimate your model. This model contains redundant indicators. The model you are interested in does not contain the repeated indicators. 
Assessing the fit of a model containing the repeated indicators leads to problems, hence, you receive this warning message as your model-implied variance-covariance matrix is not of full rank (due to the repeated indicators). Hence the matrix cannot be inverted.

We have carefully thought about implementing the repeated indicators approach properly, i.e., removing the repeated indicators after the estimation and constructing the model-implied variance-covariance matrix in accordance. However, we came to the conclusion that it is not worth the effort since the two/three-stage approach performs better and is the recommended approach, see Schuberth et al. (2020) and VanRiel et al. (2017).

The two/three-stage approach is also the default when you specidy second-order constructs in cSEM. Hence, I recommend to use this approach. The main advantage of this approach over the other approaches is that it allows for a better location of the misfit, see Schuberth et al. (2020). However, as mentioned earlier, your second-order composite is not allowed to be isolated, i.e., it must be embedded in a structural model. Otherwise, your model is not identified. 

Specifying second-order constructs is straightforward in cSEM, see an example specification in the following:
model<-'
#First-order composite
FOC1<~x1+x2
#First-order common factor
FOC2=~x3+x4
#Other construct specified as a composite
CONS1<~y1+y2
#Second-order composite
SOC<~FOC1+FOC2
CONS1~SOC'

HTH

Best regards, 
Florian 

References:
Schuberth, F., Rademaker, M. E., & Henseler, J. (2020). Estimating and assessing second-order constructs using PLS-PM: the case of composites of composites. Industrial Management & Data Systems.

Van Riel, A. C., Henseler, J., Kemény, I., & Sasovova, Z. (2017). Estimating hierarchical constructs using consistent partial least squares. Industrial management & data systems.

**Comment by shaan2020** [comment]
Dear sir,

Many thanks to you both, especially Florian for such a detailed
information. This is very helpful.

One last question: Florian sir,

can you just correct the last line of your reply  I. E. # second order
composite......


Thanks once again

**Comment by FloSchuberth** [comment]
There is written CONS1 'tilde' SOC. This line is necessary to embed the SOC in the structural model.

Best regards, 
Florian

**Comment by shaan2020** [comment]
Thnks a lot sir. I am really grateful to both of you.
