### ISSUE TITLE
R squared over 2

### ISSUE THREAD

**Issue by gitE0Z9** [M-E-Rademaker/cSEM#421]
Hi, I ran a csem model and got a construct with R squared over 2!
Is there any reason why it showed such result?

**Comment by FloSchuberth** [comment]
Interesting and actually that should not happen. Is it possible to provide your data and code used for the analysis?
Best regards, 
Florian

**Comment by gitE0Z9** [comment]
Thanks for your kindly help!
I have emailed you the data and the code.

**Comment by FloSchuberth** [comment]
Hey,

I have checked your code and the problem is that the construct correlation matrix is not positive definite, i.e., it is not a valid correlation matrix. If you use verify(.object), you can see whether your estimation is admissible.

This can happen when PLSc is applied. Since your model consists of common factor, cSEM applies PLSc by default (as PLS produces biased estimates for common factor models).

In PLSc, the correlations among the constructs are corrected for attenuation. This correction can lead to improper solutions. As a consequence, you get strange path coefficients (see also at your output, some of the path coefficients are suspiciously large) as they are based on the construct correlation matrix. Moreover, all other statistics that are based on the construct correlation matrix, e.g., the R^2, are not trustworthy.

So it is not a problem in cSEM, it is rather a problem of the data at hand.

HTH

Best regards,
Florian
