### ISSUE TITLE
R2 in cSEM is different then in lm()

### ISSUE THREAD

**Issue by influence-of-canopy-on-temperature** [M-E-Rademaker/cSEM#427]
I am running a model in cSEM, and when I use the assess() function it says that the path between my two latent variables has R2 of 0.24. However, when I extract the latent variables scores and run a simple linear model with the  lm() function, it says that the R2 is 0.12. I am attaching here my code, and the data is available at https://app.box.com/s/twt2jxx1jj5th18evj5bfmpjmnbja45t

```
require("cSEM")

# Load data
data_csem<-read.csv("data_csem.csv")

model <- "
# Structural model
YARDS ~ SOCIOECONOMIC
# Reflective measurement model
YARDS =~   YAR7 + YAR50 + YAR51 + YAR54 + YAR56    
SOCIOECONOMIC =~ SOC1 + SOC2 + +SOC5 +SOC6 
YARDS ~~ YARDS
SOCIOECONOMIC ~~ SOCIOECONOMIC
"

a_pls <- csem(.data = data_csem, .model = model, .resample_method = "bootstrap")
assess(a_pls)          #R2=0.2444

scores<-getConstructScores(a_pls)
a_lm <- lm(YARDS~SOCIOECONOMIC, data=as.data.frame(scores$Construct_scores))
summary(a_lm)          #R2 = 0.1269
```

**Comment by M-E-Rademaker** [comment]
The difference is due to the fact that you have a reflective measurement model specified and `cSEM` always disattenuates by default in this case. The documentation of the `csem()` function states:

> Composite-indicator and composite-composite correlations are properly disattenuated by default to yield consistent loadings, construct correlations, and path coefficients if any of the concepts are modeled as a common factor.

> For PLS-PM disattenuation is done using PLSc (Dijkstra and Henseler 2015).

So when you run a simple regression between the scores using `lm()` you are running a regression between *proxies* for an underyling common factor/latent variable. The R2 computed by `cSEM` is the squared correlation between the common factors/latent variables not the proxies. Hence, the difference in the R2.

If what I just wrote does not make sense to you, I suggest you start by reading Dijkstra and Henseler (2015). This should give meaning to it.

> Dijkstra TK, Henseler J (2015). “Consistent and Asymptotically Normal PLS Estimators for Linear Structural Equations.” Computational Statistics & Data Analysis, 81, 10--23.

**Comment by FloSchuberth** [comment]
In addition to Manuels response to which I totally agree, you can get a R^2 of 0.12 if you set the csem argument .disattenuate to FALSE. In this case no correction for attenuation is applied.

Moreover, you do not need to specify the variance (~~) since they are ignored in cSEM as most of the composite-based scale the weights that the variance of each construct is equal to 1.

**Comment by influence-of-canopy-on-temperature** [comment]
Thank you very much for your explanation. Sorry for my ignorance again, but would it be possible to extract construct scores that incorporate the disattenuation, or get the common factors / latent variables that were used to compute the correlation? In the end, my purpose was to extract the residues of the path between the two constructs, in order to test for spatial autocorrelation in a second step of our research.

**Comment by FloSchuberth** [comment]
In cSEM this is not possible. It might be that if you apply GSCAm (Hwang et al. 2017) that you obtain such scores. At least I vaguely remember that I have read sth like that on SEMNET. However, currently I am not aware about any implementation of this approach. I recently talked to Heungsun and he said that their approach will be soon implemented.

Another way to consider is to check whether you can express the test for spatial autorcorrelation in terms of correlations/covariances. If this is possible you can twerk around the issues of the scores.

HTH

Hwang, H.; Takane, Y. & Jung, K.
Generalized Structured Component Analysis with Uniqueness Terms for Accommodating Measurement Error
Frontiers in Psychology, 2017, 8
