### ISSUE TITLE
Setting dominant indicator in cSEM

### ISSUE THREAD

**Issue by JulianGaviriaL** [M-E-Rademaker/cSEM#436]
Dear experts,

1. Practical question:
I wonder how to set  the dominant indicators for each composite in the following model:

```
#Running model:
model <- "

  # Composite variables
  X <~ Brain_prev1 + Brain_prev2 + Brain_prev3 + Brain_prev4 + Brain_prev5
  Y <~ Brain_curr1 + Brain_curr2 + Brain_curr3 + Brain_curr4 + Brain_curr5
  
           # direct effect
             Y ~ X
         "
```
In the attempt to follow: https://rdrr.io/cran/cSEM/man/setDominantIndicator.html, I've got the next error message:

```
res <- csem(.data=myDATA,.model=model, .dominant_indicators= X$Brain_prev2, Y$Brain_curr2, .resample_method = "bootstrap", .R=999)
Error in match.arg(.approach_2ndorder) : object 'Y' not found
```

According to Benitez et al., 2020, this is recommended before the model estimation. They also stated that "dominant indicators  dictate the orientation of a construct. And it should positively correlate with the construct.  What if one of both main indicators is negative?

Many thanks in advance,

Julian.

**Comment by FloSchuberth** [comment]
Hey Julian, 

to set the dominant indicator in your, please try the following:
csem(.data=myDATA,.model=model, .dominant_indicators= c('X'='Brain_prev2','Y'='Brain_curr2'), .resample_method = "bootstrap", .R=999)

The reason to use a dominant indicator is that the sign of the weights is not uniquely determined. In PLS, the weights to form a composite are scaled such that the composite's variance is equal to 1, i.e., w_i'S_ii w_i=1. Having only this conditions allows for two solutions because also (-w_i)'S_ii(-w_i)=1. Therefore, it is recommended to choose one indicator (the dominant indicator) that dictates the orientation of the construct. However, usually the PLS results are fine without choosing such an indicator. The problem is similar to CFA if you fix the variance of the latent variable instead of choosing a scaling indicator to ensure that the model is identified. 

HTH

Best regards,
Florian
