### ISSUE TITLE
Obtaining MAE, RMSE, and Q2 values from endogenous constructs

### ISSUE THREAD

**Issue by JulianGaviriaL** [M-E-Rademaker/cSEM#440]
Dear cSEM experts,

Following-up the issue #437,  I wonder whether the cSEM package could provide the MAE, RMSE, and Q2 (i.e., prediction) values for the endogenous constructs, instead of the endogenous constructs’ indicators. Such as it has been suggested in Hair et al., 2019. P 13).

As an example, the overview provided by `predict() ` for the constructs’ indicators is complete and very user-friendly. 

Thanks in advance, 

**Reference**
Hair, J.F., Risher, J.J., Sarstedt, M., Ringle, C.M., 2019. When to use and how to report the results of PLS-SEM. Eur. Bus. Rev. 31, 2–24. https://doi.org/10.1108/EBR-11-2018-0203

**Comment by FloSchuberth** [comment]
Dear Julian, 

these metrics are currently not implemented on construct level. To be honest, I am also not sure how this should be done since to calculate the RMSE and the MAE you need to know the observed value so that we can compare it to our prediction. However, for constructs, we do not know it, thus it is not clear how these metrics should be calculated on construct level. Of course, if you come up with some formulas, we can think about an implementation. 

Best regards, 
Florian

**Comment by srk7774** [comment]
@M-E-Rademaker This is done using the blindfolding procedure. This Stone-Geisser’s Q^2 is similar to R^2.  The following information helps to get an idea of how it can be done. Look the description part. The algorithm is clearly explained. https://www.smartpls.com/documentation/algorithms-and-techniques/blindfolding

After getting Q^2, we can also calculate q^2 which is effect size similar to f^2.  Most papers report these results. 

Currently, smartpls 2.0 is free and provides blindfolding option.

**Comment by FloSchuberth** [comment]
@T-Schamberger: Can you please have a look at this issue.
