### ISSUE TITLE
References in the documentation of the verify() function

### ISSUE THREAD

**Issue by ECONshare** [M-E-Rademaker/cSEM#452]
The verify() function helpfully indicates if there is any problems with the estimation. There is 5 criterions checked. Is it possible to add to the documentation any articles or sources that indicates that these 5 criterions is important? If you do not have references for all 5 that is perfectly fine, but at least one or two reference would be very helpful.

**Comment by FloSchuberth** [comment]
Hey, 

thanks for your comment. I am not aware of a technical PLS paper that mentions that these criteria are important. However, there are some guidelines such as Benitez et al. (2020) highlighting the importance of these criteria. In the following, I give a brief explanation why I think the criteria are important:
-Standardized factor loading estimates in the context of PLS-PM equal a correlation coefficient. By definition correlation coefficients are bounded between -1 and 1. Therefore, an absolute factor loading estimate larger than one is invalid. Since the indicators and the LVs are standardized, the indicator's variance can be decomposed into squared loading (the share that is explained by the LV) and 1-squared loading (the shared that is contributed to measurement error). The two shares must sum up to one, which is not the case if the absolute standardized loading estimate is larger than 1. In the SEM literature this phenomena is also known as Heywood case. 
-Convergence of the PLS algorithm. Although the PLS estimates show their properties after one iteration, the solution is not regarded as stable in the sense of PLS-PM if the PLS has not converged.
- Positive semi-definite model-implied construct correlation matrix. By definition a correlation matrix is at least positive semi-definite. Hence, if the model-implied construct correlation matrix is not positive (semi-)definite, it is not a valid correlation matrix.
-   Positive semi-definite model-implied indicator correlation matrix. Same logic as before applies. 
- reliability estimate smaller equal to 1: Since all variables are standardized, the reliability estimate equals a squared correlation coefficient. Since correlation are bounded between -1 and 1. A squared correlation is bounded between 0 and 1. Consequently, a reliability larger than 1 is not valid. 
- 
Does this help?

Best regards, 
Florian

**Comment by ECONshare** [comment]
Hi Florian,

Thanks a lot for the elaborate answer and the references as well. Your points are good and it makes sense to check these criteria with the verify() function. 

Best
Benjamin

**Comment by FloSchuberth** [comment]
Hi Benjamin, 

you are welcome. 

Best regards, 
Flo
