### ISSUE TITLE
Multilevel modeling

### ISSUE THREAD

**Issue by mantas-t** [M-E-Rademaker/cSEM#467]
Hi, is there a way to to multilevel modeling with cSEM? 
Something similar to lavaan https://lavaan.ugent.be/tutorial/multilevel.html?

**Comment by FloSchuberth** [comment]
Hey @mantas-t, 

no, in cSEM, there is no option for multilevel modeling. 

To my knowledge, multilevel modeling is not very common in PLS-PM. I just saw some suggestions of Kock, but it seems that they are hardly used. 

Best regards, 
Florian

**Comment by mantas-t** [comment]
Hi @FloSchuberth,

Thanks for the comment.

I have longitudinal/panel data with multiple observations over time of the same subjects. There are also other clustering structure present as well e.g. some subjects belonging to the same structural group (or cluster in your terminology). However the minimum I would like to do is to account somehow for the correlation within subjects (different observations of the same subject). 
Is there a way to do something in order to account for this "non iid" situation using cSEM?

Best regards,
Mantas

**Comment by FloSchuberth** [comment]
Hey @mantas-t, 

I understand your issue. However, in cSEM there is no approach implement that takes into account correlations among error terms. I am sorry. In general I am also not aware of any approach in PLS-PM that do so. However, I proposed recently a specification that allows to estimate composite models with common SEM software. So if the reason why you use PLS-PM is because you have composites in your model, this specification might valuable for you. Moreover, it might be that you can use approach implemented in SEM software such as MPlus or lavaan to take into account the cluster structure in your data. However, I have not tested this. If you send me an email (f.schuberth@utwente.nl), I can share a copy of my paper with you.

Best regards, 
Florian
